version: "3.3"

services:
  db:
    image: mysql:5.7
    volumes:
      - prestashop-8.1-db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: prestashop
      MYSQL_USER: prestashop
      MYSQL_PASSWORD: prestashop
      MYSQL_ROOT_PASSWORD: prestashop
    ports:
      - 3313:3306
    container_name: local-prestashop-8.1-mysql

  prestashop:
    depends_on:
      - db
    image: prestashop/prestashop:latest
    ports:
      - 9012:80
      - 9446:443
    environment:
      APACHE_RUN_USER: '#1000'
      APACHE_RUN_GROUP: '#1000'
      PS_DB_HOST: db:3306
      PS_DB_USER: prestashop
      PS_DB_PASSWORD: prestashop
    volumes:
      - ./html:/var/www/html
      - ./:/var/www/html/modules/doofinder
      - ./html/ignore-folder-html-loop:/var/www/html/modules/doofinder/html
    container_name: local-web-prestashop-8.1
volumes:
  prestashop-8.1-db:
