services:
  db:
    image: mysql:5.7
    volumes:
      - prestashop-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3311:3306

  prestashop:
    depends_on:
      - db
    build:
      context: docker
      args:
        PHP_VERSION: ${PHP_VERSION}
        PS_VERSION: ${PS_VERSION}
    ports:
      - 9011:80
      - 4011:443
    environment:
      PS_DEV_MODE: 1
      DB_SERVER: db
      DB_USER: ${MYSQL_USER}
      DB_PASSWD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
      PS_INSTALL_AUTO: 1
      PS_DOMAIN: ${PS_BASE_URL}
      PS_FOLDER_ADMIN: ${PS_FOLDER_ADMIN}
      PS_ENABLE_SSL: 1
      ADMIN_MAIL: ${PS_ADMIN_EMAIL}
      ADMIN_PASSWD: ${PS_ADMIN_PASSWORD}
      # XDEBUG_CONFIG: "client_host=${XDEBUG_HOST} idekey=${XDEBUG_KEY} start_with_request=yes"
      # XDEBUG_MODE: "debug,develop"
    volumes:
      - ./html:/var/www/html
      - ./:/var/www/html/modules/doofinder
      - ./html/ignore-folder-html-loop:/var/www/html/modules/doofinder/html
volumes:
  prestashop-db:
