version: "3.3"

services:
  db:
    image: mysql:5.7
    volumes:
      - prestashop-db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: prestashop
      MYSQL_USER: prestashop
      MYSQL_PASSWORD: prestashop
      MYSQL_ROOT_PASSWORD: prestashop
    ports:
      - 3311:3306
    container_name: local-prestashop-mysql

  prestashop:
    depends_on:
      - db
    image: prestashop/prestashop:1.7
    ports:
      - 9011:80
      - 443:443
    environment:
      APACHE_RUN_USER: '#1000'
      APACHE_RUN_GROUP: '#1000'
      PS_DB_HOST: db:3306
      PS_DB_USER: prestashop
      PS_DB_PASSWORD: prestashop
    volumes:
      - ./html:/var/www/html
      - ./:/var/www/html/modules/doofinder
    container_name: local-web-prestashop
volumes:
  data: