version: "3.3"

services:
  db:
    image: mysql:5.7
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: prestashop
      MYSQL_USER: prestashop
      MYSQL_PASSWORD: prestashop
      MYSQL_ROOT_PASSWORD: prestashop
    ports:
      - 3308:3306
    container_name: local-prestashop-mysql

  prestashop:
    depends_on:
      - db
    image: prestashop/prestashop:1.7
    ports:
      - 9000:80
      - 443:443
    environment:
      PS_DB_HOST: db:3306
      PS_DB_USER: prestashop
      PS_DB_PASSWORD: prestashop
    volumes:
      - ./html:/var/www/html
    container_name: local-web-prestashop
volumes:
  data: