<?php
/**
 * @author    Doofinder
 * @copyright Doofinder
 * @license   MIT
 * @see       https://opensource.org/licenses/MIT
 */

/*
 * +---------------------------------------------------------------------------+
 * |                           *** AUTOGENERATED FILE WARNING ***              |
 * |                                                                           |
 * |  !!! THIS FILE IS AUTOGENERATED FROM A TEMPLATE !!!                       |
 * |                                                                           |
 * |  X  Any changes made to this file will be OVERWRITTEN during build!       |
 * |                                                                           |
 * |  >  To modify this file, edit the corresponding template in:              |
 * |     templates/ directory instead                                          |
 * |                                                                           |
 * |  ~  This file will be regenerated automatically!                          |
 * +---------------------------------------------------------------------------+
 */

namespace PrestaShop\Module\Doofinder\Core;

if (!defined('_PS_VERSION_')) {
    exit;
}

class DoofinderConstants
{
    const DOOMANAGER_REGION_URL = '${DOOMANAGER_REGION_URL}';
    const DOOPLUGINS_REGION_URL = '${DOOPLUGINS_REGION_URL}';
    const DOOPHOENIX_REGION_URL = '${DOOPHOENIX_REGION_URL}';
    const CONFIG_REGION_URL = '${CONFIG_REGION_URL}';
    const GS_SHORT_DESCRIPTION = 1;
    const GS_LONG_DESCRIPTION = 2;
    const VERSION = '${PLUGIN_VERSION}';
    const NAME = 'doofinder';
    const YES = 1;
    const NO = 0;
}
