name: Create Release
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  create-release:
    name: Build & Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Build
        id: vars
        run: |
          tag=${GITHUB_REF#refs/*/}
          zip_path="doofinder-prestashop.zip"
          echo "zip_path=$zip_path" >> $GITHUB_OUTPUT
          git archive --format=zip -o $zip_path --prefix doofinder/ $tag
      - name: Create release & upload asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: ${{ steps.vars.outputs.zip_path }}
