name: PHP tests
on: [push, pull_request]
jobs:
  php-linter:
    name: PHP Syntax check 5.4|5.6|7.2|7.4|8.0|8.4
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: PHP syntax checker 5.4
        uses: prestashop/github-action-php-lint/5.4@master

      - name: PHP syntax checker 5.6
        uses: prestashop/github-action-php-lint/5.6@master

      - name: PHP syntax checker 7.2
        uses: prestashop/github-action-php-lint/7.2@master

      - name: PHP syntax checker 7.4
        uses: prestashop/github-action-php-lint/7.4@master

      - name: PHP syntax checker 8.0
        uses: prestashop/github-action-php-lint/8.0@master

      - name: PHP syntax checker 8.4
        uses: prestashop/github-action-php-lint/8.4@master

  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: composer install

      - name: PHP-CS-Fixer
        run: php vendor/bin/php-cs-fixer fix --dry-run --diff --using-cache=no --rules=@PSR2
