name: Prestashop validator V2
on:
  workflow_run:
    workflows: ["PHP tests"]
    types: [completed]
jobs:
  prestashop-validator:
    if: github.event.workflow_run.conclusion == 'success'
    name: send module to validator
    runs-on: ubuntu-latest
    steps:
      - name: Send module to validator
        uses: PrestaShopCorp/github-action-validator@dev
        env:
          VALIDATOR_API_KEY: ${{ secrets.PRESTASHOP_VALIDATOR_API_KEY }}
        with:
          github_link: ${{ github.event.workflow_run.repository.full_name }}
          github_branch: ${{ github.event.workflow_run.head_branch }}
